version: '3.8'

services:
  notification-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=production
      - PORT=5555
      - CLIENT_URL=http://localhost:3333
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
      - db_data:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - notification-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - notification-server
    restart: unless-stopped
    networks:
      - notification-network
    profiles:
      - production

volumes:
  db_data:
    driver: local

networks:
  notification-network:
    driver: bridge